name: Build Snapshot

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '*.md'
      - 'docs/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '*.md'
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Build Plugin
        run: |
          chmod +x ./gradlew
          echo "SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV
          ./gradlew buildPlugin
          ./gradlew buildPluginLegacy
          mkdir upload
          zip -r data.zip data
          cp data.zip upload/
          cp build/mirai/*.jar upload/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mirai-compiler-framework-${{ env.SHA }}
          path: upload/
          if-no-files-found: error
